INSTALL PLUGIN validate_password SONAME 'validate_password';

SELECT PLUGIN_NAME, PLUGIN_STATUS FROM INFORMATION_SCHEMA.PLUGINS 
WHERE PLUGIN_NAME LIKE 'validate%';

SELECT VALIDATE_PASSWORD_STRENGTH('Crj@BbgKvkrQv&N&J45e')